// Assignment3_TestCases 
// Made by:- Meet Bharatbhai Anghan

// Generated by Selenium IDE

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void sellYourVehicleAllValidInputs2018ToyotaCamry()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Meet");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("93 Linnwood Ave");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("23 Linden Drive");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N1R 2C3");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("888-888-8888");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("meetanghan@gmail.com");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("toyota");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("camry");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2018");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("link")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".title")).Text, Is.EqualTo("2018 Toyota Camry"));
    }
    [Test]
    public void sellYourVehicleInvalidInputForEmailErrorShowingForEmailFormat()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("John");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Public");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("1234 foreign rd");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("toronto");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N1E 3C4");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("455-455-4555");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("fsfsdajda");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("honda");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("accord");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2020");
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.FindElement(By.Id("emailValidate")).Text, Is.EqualTo("* Correct Format For Email: someone@example.com"));
    }
    [Test]
    public void sellYourVehicleInvalidInputForLastNameErrorShowingLastNameFormat()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Meet");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("1234");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("34 Munch Ave");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Winnipeg");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("M1C 3D4");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("888-888-8888");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("meetpatel@gmail.com");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("honda");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("civic");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2022");
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.FindElement(By.Id("lname")).Text, Is.EqualTo("* Last Name should be in characters"));
    }
    [Test]
    public void sellYourVehicleInvalidInputForPostalCodeErrorShowingForPostalCodeFormat()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(794, 614);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Meet");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Patel");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("125 Alison Ave");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("n1r3c2");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("522-522-5555");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("meetanghan@gmail.com");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("toyota");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("camry");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2011");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".mb-1:nth-child(3)")).Click();
        Assert.That(driver.FindElement(By.Id("zipCode")).Text, Is.EqualTo("* Correct Format For PostalCode: X1X 1X1"));
    }
    [Test]
    public void sellYourVehicleInvalidPhoneNumberInputErrorForPhoneNoFormat()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Meet");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("43 Linden Cr");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'SK']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N1R 3C4");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("5555555555");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("anghan@gmail.com");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("honda");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("accord");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2017");
        driver.FindElement(By.CssSelector(".btn")).Click();
        //Assert
        Assert.That(driver.FindElement(By.Id("phone")).Text, Is.EqualTo("* Correct Format For Phone: XXX-XXX-XXXX or (XXX)XXX-XXXX"));
    }
    [Test]
    public void sellYourVehicleOmitAllInputFieldsErrorsForMissingAllInputFields()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.FindElement(By.Id("fname")).Text, Is.EqualTo("* First Name is required"));
        Assert.That(driver.FindElement(By.Id("lname")).Text, Is.EqualTo("* Last Name is required"));
        Assert.That(driver.FindElement(By.Id("house")).Text, Is.EqualTo("* Address is required"));
        Assert.That(driver.FindElement(By.Id("citi")).Text, Is.EqualTo("* City is required"));
        Assert.That(driver.FindElement(By.Id("provinceValidate")).Text, Is.EqualTo("* Please Select Province"));
        Assert.That(driver.FindElement(By.Id("zipCode")).Text, Is.EqualTo("* Postal Code is required"));
        Assert.That(driver.FindElement(By.Id("phone")).Text, Is.EqualTo("* Phone Number is required"));
        Assert.That(driver.FindElement(By.Id("emailValidate")).Text, Is.EqualTo("* Email is required"));
        Assert.That(driver.FindElement(By.Id("makeValidate")).Text, Is.EqualTo("* Make is required"));
        Assert.That(driver.FindElement(By.Id("modelValidate")).Text, Is.EqualTo("* Model is required"));
        Assert.That(driver.FindElement(By.Id("yearValidate")).Text, Is.EqualTo("* Year is required"));
    }
    [Test]
    public void sellYourVehicleOmitCityErrorForMissingCity()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Meet");
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Bharat");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("34 June Valley");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2C 3X4");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("222-222-8555");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("banghan@gmail.com");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("honda");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("accord");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2020");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".mb-1:nth-child(1)")).Click();
        Assert.That(driver.FindElement(By.Id("citi")).Text, Is.EqualTo("* City is required"));
    }
    [Test]
    public void sellYourVehicleOmitFirstNameErrorShowingForMissingFirstName()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("23 Hiton Dr");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("M1R 2C5");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("877-877-8777");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("anghan@gmail.com");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("honda");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("accord");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2014");
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.FindElement(By.Id("fname")).Text, Is.EqualTo("* First Name is required"));
    }
    [Test]
    public void sellYourVehicleOmitModelInputErrorShowingMissingModelInput()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Meet");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("87 Detal Cr");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Mississauga");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N1C 3D4");
        driver.FindElement(By.CssSelector(".row > .mb-4:nth-child(1)")).Click();
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("874-852-8521");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("anghant@gmail.com");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("honda");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2020");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(2) > .card-body")).Click();
        Assert.That(driver.FindElement(By.Id("modelValidate")).Text, Is.EqualTo("* Model is required"));
    }
    [Test]
    public void sellYourVehicleOmitSelectingProvinceErrorShowingMissingProvinceSelection()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(800, 620);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Meet");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Anhan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("67 munch Cr");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Regina");
        driver.FindElement(By.Id("province")).Click();
        driver.FindElement(By.Id("province")).Click();
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N1C 3C3");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("777-777-7777");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("anhan@gmail.com");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("honda");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("accord");
        driver.FindElement(By.Id("year")).Click();
        driver.FindElement(By.Id("year")).SendKeys("2015");
        driver.FindElement(By.CssSelector(".btn")).Click();
        Assert.That(driver.FindElement(By.Id("provinceValidate")).Text, Is.EqualTo("* Please Select Province"));
    }
    [Test]
    public void sellYourVehicleOmitYearInputErrorShowingForMissingYearInput()
    {
        driver.Navigate().GoToUrl("http://localhost/Assignment3/main.html");
        driver.Manage().Window.Size = new System.Drawing.Size(792, 612);
        driver.FindElement(By.Id("add")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Meet");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Anghan");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("32 Regina Ave");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Waterloo");
        driver.FindElement(By.Id("province")).Click();
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("V1C 2X3");
        driver.FindElement(By.Id("phoneNo")).Click();
        driver.FindElement(By.Id("phoneNo")).SendKeys("784-744-8744");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("manghan@conestogac.on.ca");
        driver.FindElement(By.Id("make")).Click();
        driver.FindElement(By.Id("make")).SendKeys("toyota");
        driver.FindElement(By.Id("model")).Click();
        driver.FindElement(By.Id("model")).SendKeys("corolla");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(2) > .card-body")).Click();
        Assert.That(driver.FindElement(By.Id("yearValidate")).Text, Is.EqualTo("* Year is required"));
    }
}
